CIRCUITPY_WIFI_SSID = "ssid_name"
CIRCUITPY_WIFI_PASSWORD = "password"
CIRCUITPY_WEB_INSTANCE_NAME = "LabMonitor"
CIRCUITPY_WEB_API_PASSWORD="passw0rd"
CIRCUITPY_WEB_API_PORT=205
sensor1 = "BME280"
sensor1TemperatureOffset = 0
sensor2 = "MCP9808"
sensor2TemperatureOffset = 0
